# Template Dockerfile that contains generic steps of building a container for reproduction packages

# Copyright 2021, Wolfgang Mauerer <wolfgang.mauerer@othr.de>
# Copyright 2021, Stefanie Scherzinger <stefanie.scherzinger@uni-passau.de>
# Copyright 2021, Stefan Klessinger <stefan.klessinger@uni-passau.de>
# SPDX-License-Identifier: MIT-0

# Start off of a long-term maintained base distribution
FROM ubuntu:20.04

MAINTAINER Stefan Klessinger <stefan.klessinger@uni-passau.de>

ENV DEBIAN_FRONTEND noninteractive
ENV LANG="C.UTF-8"
ENV LC_ALL="C.UTF-8"

# Install specified packages
ARG packages
RUN apt-get update -qq && apt-get install -qq --no-install-recommends $META_PACKAGES

# Add user
RUN useradd -m -G sudo -s /bin/bash repro && echo "repro:repro" | chpasswd
RUN usermod -a -G staff repro
USER repro
WORKDIR /home/repro

COPY --chown=repro artefacts /home/repro

$META_APPEND

RUN chmod +x /home/repro/dispatch.sh

ENTRYPOINT /home/repro/dispatch.sh

